### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by liorchaga** [jiem/my-class#4]
All the links to http://myjs.fr are broken. It's a petty because the examples and explanations there are very useful and much more informative than the readme file on github.
Is there an option to restore the broken links?

**Comment by Aldaviva** [comment]
+1, even though this repo is dead.

I have resorted to using [Archive.org's backup of my.js](http://web.archive.org/web/20120618202339/http://myjs.fr/my-class/).

**Comment by jiem** [comment]
Sorry for the delay. The links are back!

**Comment by Aldaviva** [comment]
Whoa sweet, much appreciated.
